create table if not exists products (
  id bigint generated by default as identity primary key,
  name text not null,
  qty integer not null default 0,
  price numeric not null default 0,
  desc text default '',
  reviews text default '',
  image text default '',
  category text not null default 'General Items',
  out boolean not null default false
);

create table if not exists settings (
  key text primary key,
  value text default ''
);

insert into products (name, qty, price, desc, category, out)
select * from (values
  ('Paracetamol',20,30,'Common tablet','Tablets',false),
  ('Vitamin Protein',10,499,'Protein product','Protein',false),
  ('Face Cream',8,199,'Skin care product','Skin Care',false),
  ('Bath Soap',15,55,'General bathing soap','Shampoo & Soap',false)
) as v(name,qty,price,desc,category,out)
where not exists (select 1 from products);
